[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Writing"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Talks"
  pageRef = "talks"
  weight = 40

[[main]]
  name = "Certifications"
  pageRef = "certifications"
  weight = 50

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 60

[[footer]]
  name = "Topics"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/metesec"
  weight = 20

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/mete-demirci-011057253"
  weight = 30
